services:
  bankGarupa:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=${PG_USERNAME}
      - POSTGRESQL_PASSWORD=${PG_PASSWORD}
      - POSTGRESQL_DATABASE=${PG_DATABASE}
    volumes:
      - ./src/infra/database/schema/transfer-schema.sql:/docker-entrypoint-initdb.d/transfer-schema.sql
      - schema_pg_data:/bitnami/postgresql

volumes:
  schema_pg_data:
    driver: local
